language: rust
cache: cargo
addons:
  apt:
    packages:
    - libxml2-utils
install:
  - cargo install comrak
  - pip install --user yamllint
script:
  - bash test.sh
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $ALL_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $ARTICLE_FAILURE_WEBHOOK_URL
  - ./send.sh failure $ALL_WEBHOOK_URL